Added Currency class and include a field which shows the price in USD
rchhong/comiket-tracker-bot pull request #3
Opened 2023-07-22 07:40 UTC by thebunanna

Approve plz 🙏

2023-07-22 15:35 UTC, rchhong requested changes
There's a bug that breaks the bot + some stuff that needs to be cleaned up.

2023-07-22 15:35 UTC, rchhong commented on bot.py
> +    embed.add_field(name="Price ($)", value=price_in_yen * currency.get_rate(), inline=True)
I think it would make more sense to move this logic into the currency class instead of out here.

2023-07-22 15:35 UTC, rchhong commented on currency.py
> +            self.current_rate = json["rates"]["USD"]["rate"]
Need to convert to float first.

2023-07-22 15:35 UTC, rchhong commented on bot.py
> +    embed.add_field(name="Price ($)", value=price_in_yen * currency.get_rate(), inline=True)
Also, add rounding to nearest cent.

2023-07-23 01:00 UTC, thebunanna commented
this is what happened when I decide to not test with the actual discord bot

2023-07-30 03:14 UTC, rchhong commented on .github/workflows/main.yml
I'm just going to trust you on this one for now but I'm pretty sure the env field needs to have more parameters

2023-07-30 03:15 UTC, rchhong approved these changes
Looks good to me, will clean up the prints later.

2023-07-30 03:16 UTC, merged